apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions
  namespace: prism-servers
subjects:
- kind: User
  name: sa-github-actions
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: github-actions
  apiGroup: rbac.authorization.k8s.io